apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world-container
    image: dfayad/k8s-hello-world:0.0.2
    ports:
      - containerPort: 80