name: Deploy app to EKS
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    environment: dev
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build, tag, and push docker image to Dockerhub
      env:
        REGISTRY: dfayad
        REPOSITORY: k8s-hello-world
        IMAGE_TAG: latest
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --push .

    - name: update kubeconfig
      run: aws eks update-kubeconfig --name hello-world-eks --region us-east-2


    - name: Deploy to EKS
      uses: cancue/eks-action@v0.0.2
      env:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-2
        cluster_name: hello-world-eks
      with:
        args: |
          kubectl apply -f k8s/pod.yaml
          kubectl apply -f k8s/svc-lb.yaml
