name: Deploy app to EKS
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    environment: dev
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build, tag, and push docker image to Dockerhub
      env:
        REGISTRY: dfayad
        REPOSITORY: k8s-hello-world
        IMAGE_TAG: 0.0.4
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: update kubeconfig
      run: aws eks update-kubeconfig --name hello-world-eks --region us-east-2

    - name: Set up kubectl
      uses: aws-actions/eks-credentials@v1
      with:
        cluster-name: hello-world-eks

    - name: Apply manifests
      run: |
        kubectl apply -f pod.yaml
        kubectl apply -f svc-lb.yaml